In [1]:
import mwclient
import time

site = mwclient.Site('en.wikipedia.org', clients_useragent='MyBTCAnalysisProject/1.0 (contact: twoj_mail@example.com)')
page = site.pages["Bitcoin"]

In [2]:
revs = list(page.revisions(limit=10))

c:\Users\me505\Desktop\devops\bitcoin_prices_prediction\venv_btc_predictions\Lib\site-packages\mwclient\util.py:38: DeprecationWarning: limit and api_chunk_size both specified, this is not supported! limit is deprecated, will use value of api_chunk_size
  warnings.warn(

In [3]:
revs[0]

OrderedDict([('revid', 1352953263),
             ('parentid', 1352929374),
             ('user', 'Vgbyp'),
             ('timestamp',
              time.struct_time(tm_year=2026, tm_mon=5, tm_mday=7, tm_hour=6, tm_min=30, tm_sec=4, tm_wday=3, tm_yday=127, tm_isdst=-1)),
             ('comment',
              'Reverted 1 edit by [[Special:Contributions/Pinkyquecha|Pinkyquecha]] ([[User talk:Pinkyquecha|talk]]): Per [[WP:CRYSTAL]]')])

In [4]:
revs = sorted(revs, key=lambda rev: rev["timestamp"])

In [5]:
revs[0]

OrderedDict([('revid', 275832581),
             ('parentid', 0),
             ('user', 'Pratyeka'),
             ('timestamp',
              time.struct_time(tm_year=2009, tm_mon=3, tm_mday=8, tm_hour=16, tm_min=41, tm_sec=7, tm_wday=6, tm_yday=67, tm_isdst=-1)),
             ('comment', 'creation (stub)')])

In [6]:
import torch
import builtins

# To "wstrzykuje" torch wszędzie, nawet do wnętrza innych bibliotek
builtins.torch = torch 

from transformers import pipeline

# Teraz spróbuj uruchomić pipeline
sentiment_pipeline = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english", device=-1)

def find_sentiment(text):
    sent = sentiment_pipeline([text[:250]])[0]
    score = sent["score"]
    if sent["label"] =="NEGATIVE":
        score *= -1
    return score

c:\Users\me505\Desktop\devops\bitcoin_prices_prediction\venv_btc_predictions\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\me505\Desktop\devops\bitcoin_prices_prediction\venv_btc_predictions\Lib\site-packages\huggingface_hub\file_download.py:1842: DeprecationWarning: hf_xet.download_files() is deprecated. Use XetSession().new_file_download_group().start_download_file() instead.
  xet_get(
c:\Users\me505\Desktop\devops\bitcoin_prices_prediction\venv_btc_predictions\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\me505\.cache\huggingface\hub\models--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 104/104 [00:00<00:00, 14823.88it/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\me505\Desktop\devops\bitcoin_prices_prediction\venv_btc_predictions\Lib\site-packages\transformers\models\bert\tokenization_bert.py:104: DeprecationWarning: Deprecated in 0.9.0: WordPiece.__init__ will not create from files anymore, try `WordPiece.from_file` instead
  self._tokenizer = Tokenizer(WordPiece(self._vocab, unk_token=str(unk_token)))

In [11]:
find_sentiment("Bye")

-0.968428373336792

In [13]:
edits = {}

for rev in revs:
    date = time.strftime("%Y-%m-%d", rev["timestamp"])

    if date not in edits:
        edits[date] = dict(sentiments=list(), edit_count=0)

    edits[date]["edit_count"] += 1

    comment = rev.get("comment", "")
    edits[date]["sentiments"].append(find_sentiment(comment))

In [19]:
from statistics import mean

for key in edits:
    if len(edits[key]["sentiments"]) > 0:
        edits[key]["sentiment"] = mean(edits[key]["sentiments"])
        edits[key]["neg_sentiment"] = len([s for s in edits[key]["sentiments"] if s < 0]) / len(edits[key]["sentiments"])
    else: 
        edits[key]["sentiment"] = 0
        edits[key]["meg_sentiment"] = 0

    del edits[key]["sentiments"]

KeyError: 'sentiments'

In [20]:
edits

{'2009-03-08': {'edit_count': 4,
  'sentiment': -0.5505250245332718,
  'neg_sentiment': 0.75},
 '2009-08-05': {'edit_count': 1,
  'sentiment': 0.748120903968811,
  'neg_sentiment': 0.0},
 '2009-08-06': {'edit_count': 2,
  'sentiment': 0.9957457184791565,
  'neg_sentiment': 0.0},
 '2009-08-14': {'edit_count': 1,
  'sentiment': 0.930020809173584,
  'neg_sentiment': 0.0},
 '2009-10-13': {'edit_count': 2,
  'sentiment': -0.22750118374824524,
  'neg_sentiment': 0.5},
 '2009-11-18': {'edit_count': 1,
  'sentiment': 0.883950412273407,
  'neg_sentiment': 0.0},
 '2009-12-08': {'edit_count': 1,
  'sentiment': -0.9869275689125061,
  'neg_sentiment': 1.0},
 '2009-12-17': {'edit_count': 1,
  'sentiment': -0.9975171089172363,
  'neg_sentiment': 1.0},
 '2010-02-23': {'edit_count': 1,
  'sentiment': -0.9994946718215942,
  'neg_sentiment': 1.0},
 '2010-03-18': {'edit_count': 1,
  'sentiment': 0.8758773803710938,
  'neg_sentiment': 0.0},
 '2010-04-13': {'edit_count': 4,
  'sentiment': 0.8443556129932404,
  'neg_sentiment': 0.0},
 '2010-04-15': {'edit_count': 8,
  'sentiment': 0.5781013518571854,
  'neg_sentiment': 0.125},
 '2010-04-28': {'edit_count': 2,
  'sentiment': -0.12094306945800781,
  'neg_sentiment': 0.5},
 '2010-05-13': {'edit_count': 1,
  'sentiment': -0.9664838314056396,
  'neg_sentiment': 1.0},
 '2010-06-17': {'edit_count': 2,
  'sentiment': 0.9957457184791565,
  'neg_sentiment': 0.0},
 '2010-06-18': {'edit_count': 9,
  'sentiment': 0.3589187065760295,
  'neg_sentiment': 0.3333333333333333},
 '2010-06-19': {'edit_count': 1,
  'sentiment': 0.9875591397285461,
  'neg_sentiment': 0.0},
 '2010-06-20': {'edit_count': 3,
  'sentiment': 0.9683796962102255,
  'neg_sentiment': 0.0},
 '2010-06-21': {'edit_count': 7,
  'sentiment': 0.6157867056982858,
  'neg_sentiment': 0.14285714285714285},
 '2010-06-23': {'edit_count': 4,
  'sentiment': 0.8549631536006927,
  'neg_sentiment': 0.0},
 '2010-06-28': {'edit_count': 4,
  'sentiment': 0.28316400945186615,
  'neg_sentiment': 0.25},
 '2010-06-29': {'edit_count': 1,
  'sentiment': 0.748120903968811,
  'neg_sentiment': 0.0},
 '2010-07-05': {'edit_count': 1,
  'sentiment': 0.936066746711731,
  'neg_sentiment': 0.0},
 '2010-07-07': {'edit_count': 2,
  'sentiment': -0.15275689959526062,
  'neg_sentiment': 0.5},
 '2010-07-08': {'edit_count': 2,
  'sentiment': 0.019024938344955444,
  'neg_sentiment': 0.5},
 '2010-07-09': {'edit_count': 1,
  'sentiment': -0.9049851894378662,
  'neg_sentiment': 1.0},
 '2010-07-11': {'edit_count': 13,
  'sentiment': 0.32116182950826794,
  'neg_sentiment': 0.3076923076923077},
 '2010-07-12': {'edit_count': 9,
  'sentiment': -0.2877998153368632,
  'neg_sentiment': 0.6666666666666666},
 '2010-07-13': {'edit_count': 4,
  'sentiment': 0.8065185546875,
  'neg_sentiment': 0.0},
 '2010-07-14': {'edit_count': 4,
  'sentiment': -0.060813188552856445,
  'neg_sentiment': 0.5},
 '2010-07-15': {'edit_count': 4,
  'sentiment': -0.8949348777532578,
  'neg_sentiment': 1.0},
 '2010-07-16': {'edit_count': 6,
  'sentiment': 0.9474905033906301,
  'neg_sentiment': 0.0},
 '2010-07-18': {'edit_count': 2,
  'sentiment': -0.19054386019706726,
  'neg_sentiment': 0.5},
 '2010-07-19': {'edit_count': 4,
  'sentiment': 0.8687809705734253,
  'neg_sentiment': 0.0},
 '2010-07-21': {'edit_count': 17,
  'sentiment': -0.535709072561825,
  'neg_sentiment': 0.7647058823529411},
 '2010-07-22': {'edit_count': 1,
  'sentiment': -0.9933270215988159,
  'neg_sentiment': 1.0},
 '2010-07-25': {'edit_count': 4,
  'sentiment': -0.06201544404029846,
  'neg_sentiment': 0.5},
 '2010-07-29': {'edit_count': 3,
  'sentiment': 0.3377017378807068,
  'neg_sentiment': 0.3333333333333333},
 '2010-08-03': {'edit_count': 3,
  'sentiment': -0.9907000064849854,
  'neg_sentiment': 1.0},
 '2010-08-12': {'edit_count': 9,
  'sentiment': 0.25904009077284074,
  'neg_sentiment': 0.3333333333333333},
 '2010-08-14': {'edit_count': 1,
  'sentiment': -0.9994552731513977,
  'neg_sentiment': 1.0},
 '2010-08-18': {'edit_count': 1,
  'sentiment': -0.999642014503479,
  'neg_sentiment': 1.0},
 '2010-08-21': {'edit_count': 1,
  'sentiment': -0.9951968789100647,
  'neg_sentiment': 1.0},
 '2010-09-20': {'edit_count': 1,
  'sentiment': -0.9341223239898682,
  'neg_sentiment': 1.0},
 '2010-09-26': {'edit_count': 2,
  'sentiment': -0.9957654178142548,
  'neg_sentiment': 1.0},
 '2010-09-27': {'edit_count': 2,
  'sentiment': -0.9451581537723541,
  'neg_sentiment': 1.0},
 '2010-09-29': {'edit_count': 1,
  'sentiment': -0.9989383816719055,
  'neg_sentiment': 1.0},
 '2010-10-02': {'edit_count': 1,
  'sentiment': -0.9153560996055603,
  'neg_sentiment': 1.0},
 '2010-10-05': {'edit_count': 1,
  'sentiment': -0.994151771068573,
  'neg_sentiment': 1.0},
 '2010-10-19': {'edit_count': 1,
  'sentiment': 0.6267770528793335,
  'neg_sentiment': 0.0},
 '2010-11-10': {'edit_count': 1,
  'sentiment': 0.9957578778266907,
  'neg_sentiment': 0.0},
 '2010-11-11': {'edit_count': 1,
  'sentiment': -0.9928996562957764,
  'neg_sentiment': 1.0},
 '2010-11-25': {'edit_count': 1,
  'sentiment': -0.9625310301780701,
  'neg_sentiment': 1.0},
 '2010-11-26': {'edit_count': 3,
  'sentiment': -0.2969606916109721,
  'neg_sentiment': 0.6666666666666666},
 '2010-11-28': {'edit_count': 1,
  'sentiment': -0.9982038736343384,
  'neg_sentiment': 1.0},
 '2010-12-01': {'edit_count': 1,
  'sentiment': 0.9957578778266907,
  'neg_sentiment': 0.0},
 '2010-12-05': {'edit_count': 3,
  'sentiment': 0.2574625412623088,
  'neg_sentiment': 0.3333333333333333},
 '2010-12-10': {'edit_count': 15,
  'sentiment': 0.36348582108815514,
  'neg_sentiment': 0.26666666666666666},
 '2010-12-11': {'edit_count': 50,
  'sentiment': 0.22862035036087036,
  'neg_sentiment': 0.32},
 '2010-12-12': {'edit_count': 17,
  'sentiment': -0.3360810875892639,
  'neg_sentiment': 0.6470588235294118},
 '2010-12-13': {'edit_count': 12,
  'sentiment': -0.8279572327931722,
  'neg_sentiment': 0.9166666666666666},
 '2010-12-14': {'edit_count': 49,
  'sentiment': -0.3559756923695,
  'neg_sentiment': 0.6938775510204082},
 '2010-12-15': {'edit_count': 19,
  'sentiment': -0.15530421545631007,
  'neg_sentiment': 0.5789473684210527},
 '2010-12-16': {'edit_count': 11,
  'sentiment': -0.6393263936042786,
  'neg_sentiment': 0.8181818181818182},
 '2010-12-17': {'edit_count': 4,
  'sentiment': -0.8237834572792053,
  'neg_sentiment': 1.0},
 '2010-12-18': {'edit_count': 2,
  'sentiment': -0.9995501041412354,
  'neg_sentiment': 1.0},
 '2010-12-19': {'edit_count': 5,
  'sentiment': -0.836007010936737,
  'neg_sentiment': 1.0},
 '2010-12-20': {'edit_count': 22,
  'sentiment': -0.2894133979623968,
  'neg_sentiment': 0.6363636363636364},
 '2010-12-21': {'edit_count': 27,
  'sentiment': -0.3799964255756802,
  'neg_sentiment': 0.6666666666666666},
 '2010-12-22': {'edit_count': 25,
  'sentiment': -0.4561320209503174,
  'neg_sentiment': 0.72},
 '2010-12-23': {'edit_count': 2,
  'sentiment': 0.9408825039863586,
  'neg_sentiment': 0.0},
 '2010-12-24': {'edit_count': 1,
  'sentiment': -0.9991777539253235,
  'neg_sentiment': 1.0},
 '2011-01-01': {'edit_count': 1,
  'sentiment': 0.9105640053749084,
  'neg_sentiment': 0.0},
 '2011-01-06': {'edit_count': 1,
  'sentiment': -0.9996631145477295,
  'neg_sentiment': 1.0},
 '2011-01-07': {'edit_count': 3,
  'sentiment': 0.16846142212549844,
  'neg_sentiment': 0.3333333333333333},
 '2011-01-10': {'edit_count': 4,
  'sentiment': -0.06684882938861847,
  'neg_sentiment': 0.5},
 '2011-01-11': {'edit_count': 2,
  'sentiment': -0.9993845224380493,
  'neg_sentiment': 1.0},
 '2011-01-14': {'edit_count': 2,
  'sentiment': -0.17865502834320068,
  'neg_sentiment': 0.5},
 '2011-01-16': {'edit_count': 10,
  'sentiment': -0.3019544959068298,
  'neg_sentiment': 0.6},
 '2011-01-17': {'edit_count': 8,
  'sentiment': -0.06488822400569916,
  'neg_sentiment': 0.5},
 '2011-01-20': {'edit_count': 1,
  'sentiment': -0.6644998788833618,
  'neg_sentiment': 1.0},
 '2011-01-21': {'edit_count': 6,
  'sentiment': -0.0909172793229421,
  'neg_sentiment': 0.5},
 '2011-01-22': {'edit_count': 1,
  'sentiment': -0.9456276297569275,
  'neg_sentiment': 1.0},
 '2011-01-24': {'edit_count': 4,
  'sentiment': -0.47818276286125183,
  'neg_sentiment': 0.75},
 '2011-01-25': {'edit_count': 1,
  'sentiment': -0.5590019226074219,
  'neg_sentiment': 1.0},
 '2011-01-26': {'edit_count': 1,
  'sentiment': -0.9716882705688477,
  'neg_sentiment': 1.0},
 '2011-01-29': {'edit_count': 2,
  'sentiment': -0.7818921208381653,
  'neg_sentiment': 1.0},
 '2011-01-31': {'edit_count': 1,
  'sentiment': -0.9942212104797363,
  'neg_sentiment': 1.0},
 '2011-02-01': {'edit_count': 3,
  'sentiment': -0.9960161050160726,
  'neg_sentiment': 1.0},
 '2011-02-04': {'edit_count': 1,
  'sentiment': -0.9996967315673828,
  'neg_sentiment': 1.0},
 '2011-02-05': {'edit_count': 2,
  'sentiment': -0.9946050345897675,
  'neg_sentiment': 1.0},
 '2011-02-06': {'edit_count': 6,
  'sentiment': -0.6925411919752756,
  'neg_sentiment': 0.8333333333333334},
 '2011-02-10': {'edit_count': 8,
  'sentiment': -0.33531538397073746,
  'neg_sentiment': 0.625},
 '2011-02-11': {'edit_count': 8,
  'sentiment': 0.39717745780944824,
  'neg_sentiment': 0.25},
 '2011-02-12': {'edit_count': 5,
  'sentiment': -0.578158152103424,
  'neg_sentiment': 0.8},
 '2011-02-13': {'edit_count': 2,
  'sentiment': -0.7603687942028046,
  'neg_sentiment': 1.0},
 '2011-02-14': {'edit_count': 2,
  'sentiment': -0.9968923032283783,
  'neg_sentiment': 1.0},
 '2011-02-15': {'edit_count': 3,
  'sentiment': -0.41021567583084106,
  'neg_sentiment': 0.6666666666666666},
 '2011-02-17': {'edit_count': 4,
  'sentiment': -0.08251091837882996,
  'neg_sentiment': 0.5},
 '2011-02-18': {'edit_count': 4,
  'sentiment': -0.8350167125463486,
  'neg_sentiment': 1.0},
 '2011-02-20': {'edit_count': 1,
  'sentiment': -0.9961812496185303,
  'neg_sentiment': 1.0},
 '2011-02-23': {'edit_count': 5,
  'sentiment': 0.09343531131744384,
  'neg_sentiment': 0.4},
 '2011-02-24': {'edit_count': 1,
  'sentiment': 0.9833250045776367,
  'neg_sentiment': 0.0},
 '2011-02-25': {'edit_count': 5,
  'sentiment': -0.5711944937705994,
  'neg_sentiment': 0.8},
 '2011-02-26': {'edit_count': 2,
  'sentiment': 0.8703857958316803,
  'neg_sentiment': 0.0},
 '2011-02-28': {'edit_count': 2,
  'sentiment': 0.20266082882881165,
  'neg_sentiment': 0.5},
 '2011-03-01': {'edit_count': 1,
  'sentiment': 0.8048112988471985,
  'neg_sentiment': 0.0},
 '2011-03-04': {'edit_count': 2,
  'sentiment': 0.8691599369049072,
  'neg_sentiment': 0.0},
 '2011-03-07': {'edit_count': 6,
  'sentiment': -0.03756417830785116,
  'neg_sentiment': 0.5},
 '2011-03-08': {'edit_count': 4,
  'sentiment': -0.5860640555620193,
  'neg_sentiment': 0.75},
 '2011-03-11': {'edit_count': 3,
  'sentiment': 0.29068662722905475,
  'neg_sentiment': 0.3333333333333333},
 '2011-03-12': {'edit_count': 1,
  'sentiment': -0.9923986792564392,
  'neg_sentiment': 1.0},
 '2011-03-13': {'edit_count': 1,
  'sentiment': -0.6153934597969055,
  'neg_sentiment': 1.0},
 '2011-03-14': {'edit_count': 2,
  'sentiment': -0.9953401684761047,
  'neg_sentiment': 1.0},
 '2011-03-15': {'edit_count': 1,
  'sentiment': -0.9711605310440063,
  'neg_sentiment': 1.0},
 '2011-03-17': {'edit_count': 1,
  'sentiment': -0.9251040816307068,
  'neg_sentiment': 1.0},
 '2011-03-18': {'edit_count': 2,
  'sentiment': -0.05015981197357178,
  'neg_sentiment': 0.5},
 '2011-03-19': {'edit_count': 1,
  'sentiment': -0.9962666630744934,
  'neg_sentiment': 1.0},
 '2011-03-20': {'edit_count': 5,
  'sentiment': -0.592511510848999,
  'neg_sentiment': 0.8},
 '2011-03-21': {'edit_count': 1,
  'sentiment': 0.8048112988471985,
  'neg_sentiment': 0.0},
 '2011-03-22': {'edit_count': 1,
  'sentiment': 0.8048112988471985,
  'neg_sentiment': 0.0},
 '2011-03-23': {'edit_count': 4,
  'sentiment': -0.49070802330970764,
  'neg_sentiment': 0.75},
 '2011-03-24': {'edit_count': 1,
  'sentiment': -0.9965630173683167,
  'neg_sentiment': 1.0},
 '2011-03-25': {'edit_count': 8,
  'sentiment': -0.3314574882388115,
  'neg_sentiment': 0.625},
 '2011-03-26': {'edit_count': 4,
  'sentiment': -0.12413477897644043,
  'neg_sentiment': 0.5},
 '2011-03-28': {'edit_count': 3,
  'sentiment': -0.3978620767593384,
  'neg_sentiment': 0.6666666666666666},
 '2011-03-29': {'edit_count': 5,
  'sentiment': -0.21896153688430786,
  'neg_sentiment': 0.6},
 '2011-03-30': {'edit_count': 1,
  'sentiment': 0.8153417110443115,
  'neg_sentiment': 0.0},
 '2011-04-02': {'edit_count': 4,
  'sentiment': -0.5029853731393814,
  'neg_sentiment': 0.75},
 '2011-04-04': {'edit_count': 4,
  'sentiment': 0.3119432330131531,
  'neg_sentiment': 0.25},
 '2011-04-05': {'edit_count': 1,
  'sentiment': -0.9985226988792419,
  'neg_sentiment': 1.0},
 '2011-04-06': {'edit_count': 7,
  'sentiment': 0.339314946106502,
  'neg_sentiment': 0.2857142857142857},
 '2011-04-09': {'edit_count': 2,
  'sentiment': 0.009099960327148438,
  'neg_sentiment': 0.5},
 '2011-04-11': {'edit_count': 5,
  'sentiment': -0.25824402570724486,
  'neg_sentiment': 0.6},
 '2011-04-12': {'edit_count': 10,
  'sentiment': 0.27081133127212526,
  'neg_sentiment': 0.3},
 '2011-04-13': {'edit_count': 5,
  'sentiment': -0.6402590274810791,
  'neg_sentiment': 0.8},
 '2011-04-14': {'edit_count': 7,
  'sentiment': -0.49997247968401226,
  'neg_sentiment': 0.7142857142857143},
 '2011-04-16': {'edit_count': 13,
  'sentiment': -0.3079339082424457,
  'neg_sentiment': 0.6153846153846154},
 '2011-04-17': {'edit_count': 2,
  'sentiment': 0.9950544536113739,
  'neg_sentiment': 0.0},
 '2011-04-18': {'edit_count': 2,
  'sentiment': -0.9971082508563995,
  'neg_sentiment': 1.0},
 '2011-04-19': {'edit_count': 8,
  'sentiment': -0.49243123829364777,
  'neg_sentiment': 0.75},
 '2011-04-20': {'edit_count': 3,
  'sentiment': -0.9985311031341553,
  'neg_sentiment': 1.0},
 '2011-04-21': {'edit_count': 2,
  'sentiment': -0.12399929761886597,
  'neg_sentiment': 0.5},
 '2011-04-22': {'edit_count': 3,
  'sentiment': 0.2815057436625163,
  'neg_sentiment': 0.3333333333333333},
 '2011-04-24': {'edit_count': 1,
  'sentiment': 0.655488133430481,
  'neg_sentiment': 0.0},
 '2011-04-25': {'edit_count': 1,
  'sentiment': -0.995245635509491,
  'neg_sentiment': 1.0},
 '2011-04-26': {'edit_count': 3,
  'sentiment': 0.286892831325531,
  'neg_sentiment': 0.3333333333333333},
 '2011-04-27': {'edit_count': 8,
  'sentiment': -0.302131325006485,
  'neg_sentiment': 0.625},
 '2011-04-28': {'edit_count': 3,
  'sentiment': -0.35738585392634076,
  'neg_sentiment': 0.6666666666666666},
 '2011-04-29': {'edit_count': 5,
  'sentiment': 0.10088957548141479,
  'neg_sentiment': 0.4},
 '2011-04-30': {'edit_count': 1,
  'sentiment': 0.990734338760376,
  'neg_sentiment': 0.0},
 '2011-05-02': {'edit_count': 5,
  'sentiment': -0.22274837493896485,
  'neg_sentiment': 0.6},
 '2011-05-03': {'edit_count': 2,
  'sentiment': 0.694172203540802,
  'neg_sentiment': 0.0},
 '2011-05-04': {'edit_count': 1,
  'sentiment': 0.930020809173584,
  'neg_sentiment': 0.0},
 '2011-05-05': {'edit_count': 12,
  'sentiment': -0.046454002459843956,
  'neg_sentiment': 0.5},
 '2011-05-06': {'edit_count': 5,
  'sentiment': -0.5827880501747131,
  'neg_sentiment': 0.8},
 '2011-05-08': {'edit_count': 2,
  'sentiment': -0.9612819254398346,
  'neg_sentiment': 1.0},
 '2011-05-09': {'edit_count': 2,
  'sentiment': 0.8390708565711975,
  'neg_sentiment': 0.0},
 '2011-05-10': {'edit_count': 1,
  'sentiment': 0.874821662902832,
  'neg_sentiment': 0.0},
 '2011-05-11': {'edit_count': 1,
  'sentiment': 0.874821662902832,
  'neg_sentiment': 0.0},
 '2011-05-12': {'edit_count': 5,
  'sentiment': -0.27203903198242185,
  'neg_sentiment': 0.6},
 '2011-05-14': {'edit_count': 2,
  'sentiment': -0.15279197692871094,
  'neg_sentiment': 0.5},
 '2011-05-15': {'edit_count': 4,
  'sentiment': 0.33516012132167816,
  'neg_sentiment': 0.25},
 '2011-05-16': {'edit_count': 7,
  'sentiment': 0.1032388550894601,
  'neg_sentiment': 0.42857142857142855},
 '2011-05-17': {'edit_count': 11,
  'sentiment': -0.16553884744644165,
  'neg_sentiment': 0.5454545454545454},
 '2011-05-18': {'edit_count': 10,
  'sentiment': -0.1891341030597687,
  'neg_sentiment': 0.6},
 '2011-05-19': {'edit_count': 24,
  'sentiment': -0.6198490609725317,
  'neg_sentiment': 0.7916666666666666},
 '2011-05-20': {'edit_count': 7,
  'sentiment': -0.4990231565066746,
  'neg_sentiment': 0.7142857142857143},
 '2011-05-21': {'edit_count': 5,
  'sentiment': -0.594145655632019,
  'neg_sentiment': 0.8},
 '2011-05-22': {'edit_count': 19,
  'sentiment': -0.5031611605694419,
  'neg_sentiment': 0.7368421052631579},
 '2011-05-23': {'edit_count': 9,
  'sentiment': -0.7745044893688626,
  'neg_sentiment': 0.8888888888888888},
 '2011-05-24': {'edit_count': 13,
  'sentiment': -0.5396882066359887,
  'neg_sentiment': 0.7692307692307693},
 '2011-05-25': {'edit_count': 8,
  'sentiment': -0.08465512841939926,
  'neg_sentiment': 0.5},
 '2011-05-26': {'edit_count': 27,
  'sentiment': -0.3999680346912808,
  'neg_sentiment': 0.7037037037037037},
 '2011-05-27': {'edit_count': 8,
  'sentiment': -0.02957908809185028,
  'neg_sentiment': 0.5},
 '2011-05-28': {'edit_count': 7,
  'sentiment': -0.589052643094744,
  'neg_sentiment': 0.8571428571428571},
 '2011-05-29': {'edit_count': 3,
  'sentiment': -0.21549497048060098,
  'neg_sentiment': 0.6666666666666666},
 '2011-05-30': {'edit_count': 5,
  'sentiment': -0.28138165473937987,
  'neg_sentiment': 0.6},
 '2011-05-31': {'edit_count': 8,
  'sentiment': -0.0666583850979805,
  'neg_sentiment': 0.5},
 '2011-06-01': {'edit_count': 12,
  'sentiment': 0.4635826200246811,
  'neg_sentiment': 0.25},
 '2011-06-02': {'edit_count': 16,
  'sentiment': -0.2581380270421505,
  'neg_sentiment': 0.625},
 '2011-06-03': {'edit_count': 41,
  'sentiment': -0.3556326744033069,
  'neg_sentiment': 0.6585365853658537},
 '2011-06-04': {'edit_count': 2,
  'sentiment': 0.0008401572704315186,
  'neg_sentiment': 0.5},
 '2011-06-05': {'edit_count': 9,
  'sentiment': 0.4090726375579834,
  'neg_sentiment': 0.2222222222222222},
 '2011-06-06': {'edit_count': 12,
  'sentiment': -0.8159240136543909,
  'neg_sentiment': 0.9166666666666666},
 '2011-06-07': {'edit_count': 5,
  'sentiment': 0.19168769121170043,
  'neg_sentiment': 0.4},
 '2011-06-08': {'edit_count': 5,
  'sentiment': 0.19756342172622682,
  'neg_sentiment': 0.4},
 '2011-06-09': {'edit_count': 13,
  'sentiment': 0.3229097769810603,
  'neg_sentiment': 0.3076923076923077},
 '2011-06-10': {'edit_count': 7,
  'sentiment': 0.5857170394488743,
  'neg_sentiment': 0.14285714285714285},
 '2011-06-11': {'edit_count': 27,
  'sentiment': -0.6540296254334627,
  'neg_sentiment': 0.8148148148148148},
 '2011-06-12': {'edit_count': 49,
  'sentiment': -0.5573636962442982,
  'neg_sentiment': 0.7755102040816326},
 '2011-06-13': {'edit_count': 45,
  'sentiment': -0.2917060361968146,
  'neg_sentiment': 0.6444444444444445},
 '2011-06-14': {'edit_count': 26,
  'sentiment': -0.8288832329786741,
  'neg_sentiment': 0.9230769230769231},
 '2011-06-15': {'edit_count': 28,
  'sentiment': -0.3627498767205647,
  'neg_sentiment': 0.6785714285714286},
 '2011-06-16': {'edit_count': 31,
  'sentiment': -0.4683318772623616,
  'neg_sentiment': 0.7419354838709677},
 '2011-06-17': {'edit_count': 50,
  'sentiment': -0.482288703918457,
  'neg_sentiment': 0.74},
 '2011-06-18': {'edit_count': 78,
  'sentiment': -0.33036840496919095,
  'neg_sentiment': 0.6538461538461539},
 '2011-06-19': {'edit_count': 24,
  'sentiment': -0.4603527660171191,
  'neg_sentiment': 0.7083333333333334},
 '2011-06-20': {'edit_count': 44,
  'sentiment': -0.06140111793171276,
  'neg_sentiment': 0.5227272727272727},
 '2011-06-21': {'edit_count': 22,
  'sentiment': -0.6531902253627777,
  'neg_sentiment': 0.8181818181818182},
 '2011-06-22': {'edit_count': 16,
  'sentiment': -0.640851553529501,
  'neg_sentiment': 0.8125},
 '2011-06-23': {'edit_count': 14,
  'sentiment': -0.48162523763520376,
  'neg_sentiment': 0.7142857142857143},
 '2011-06-24': {'edit_count': 13,
  'sentiment': -0.4698865001018231,
  'neg_sentiment': 0.7692307692307693},
 '2011-06-25': {'edit_count': 8,

In [21]:
import pandas as pd

edits_df = pd.DataFrame.from_dict(edits, orient="index")

In [22]:
edits_df

            edit_count  sentiment  neg_sentiment
2009-03-08           4  -0.550525           0.75
2009-08-05           1   0.748121           0.00
2009-08-06           2   0.995746           0.00
2009-08-14           1   0.930021           0.00
2009-10-13           2  -0.227501           0.50
...                ...        ...            ...
2026-04-10           1  -0.984083           1.00
2026-04-14           1  -0.959644           1.00
2026-04-20           1   0.995622           0.00
2026-05-02           1  -0.999585           1.00
2026-05-07           2   0.003972           0.50

[2833 rows x 3 columns]

In [23]:
edits_df.index = pd.to_datetime(edits_df.index)

In [25]:
from datetime import datetime
dates = pd.date_range(start="2009-03-08", end=datetime.today())

In [26]:
dates

DatetimeIndex(['2009-03-08', '2009-03-09', '2009-03-10', '2009-03-11',
               '2009-03-12', '2009-03-13', '2009-03-14', '2009-03-15',
               '2009-03-16', '2009-03-17',
               ...
               '2026-05-03', '2026-05-04', '2026-05-05', '2026-05-06',
               '2026-05-07', '2026-05-08', '2026-05-09', '2026-05-10',
               '2026-05-11', '2026-05-12'],
              dtype='datetime64[us]', length=6275, freq='D')

In [27]:
edits_df = edits_df.reindex(dates, fill_value=0)

In [28]:
edits_df

            edit_count  sentiment  neg_sentiment
2009-03-08           4  -0.550525           0.75
2009-03-09           0   0.000000           0.00
2009-03-10           0   0.000000           0.00
2009-03-11           0   0.000000           0.00
2009-03-12           0   0.000000           0.00
...                ...        ...            ...
2026-05-08           0   0.000000           0.00
2026-05-09           0   0.000000           0.00
2026-05-10           0   0.000000           0.00
2026-05-11           0   0.000000           0.00
2026-05-12           0   0.000000           0.00

[6275 rows x 3 columns]

In [29]:
rolling_edits = edits_df.rolling(30).mean()

In [30]:
rolling_edits

            edit_count  sentiment  neg_sentiment
2009-03-08         NaN        NaN            NaN
2009-03-09         NaN        NaN            NaN
2009-03-10         NaN        NaN            NaN
2009-03-11         NaN        NaN            NaN
2009-03-12         NaN        NaN            NaN
...                ...        ...            ...
2026-05-08    0.200000  -0.064791       0.116667
2026-05-09    0.200000  -0.064791       0.116667
2026-05-10    0.166667  -0.031988       0.083333
2026-05-11    0.166667  -0.031988       0.083333
2026-05-12    0.166667  -0.031988       0.083333

[6275 rows x 3 columns]

In [31]:
rolling_edits = rolling_edits.dropna()
rolling_edits

            edit_count  sentiment  neg_sentiment
2009-04-06    0.133333  -0.018351       0.025000
2009-04-07    0.000000   0.000000       0.000000
2009-04-08    0.000000   0.000000       0.000000
2009-04-09    0.000000   0.000000       0.000000
2009-04-10    0.000000   0.000000       0.000000
...                ...        ...            ...
2026-05-08    0.200000  -0.064791       0.116667
2026-05-09    0.200000  -0.064791       0.116667
2026-05-10    0.166667  -0.031988       0.083333
2026-05-11    0.166667  -0.031988       0.083333
2026-05-12    0.166667  -0.031988       0.083333

[6246 rows x 3 columns]

In [32]:
rolling_edits.to_csv("wikipedia_edits.csv")

In [ ]:
#downloading BTC data